server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/clinica_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5433/clinica_db
    user: admin
    password: admin123
  jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
          default_schema: user_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

internal:
  gateway:
    secret: ${INTERNAL_GATEWAY_SECRET:5rO2rtldA8350502DreTcvFu9n2s8v7Xo1j6z9w0}
