server:
  port: ${SERVER_PORT:8081}

spring:
  flyway:
    enabled: false
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/clinica_db?currentSchema=auth_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    open-in-view: false
    properties:
        hibernate:
          format_sql: true
          default_schema: auth_service

jwt:
  secret: ${JWT_SECRET:Zd2W3jBD8D2xFUSNPywUHDFeuFunANkdKKnaIQzFjbj}
  expiration: ${JWT_EXPIRATION:3600000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

internal:
  gateway:
    secret: ${INTERNAL_GATEWAY_SECRET:5rO2rtldA8350502DreTcvFu9n2s8v7Xo1j6z9w0}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
