server:
  port: ${SERVER_PORT:8081}

spring:
  flyway:
    enabled: true
    schemas: auth_service
    default-schema: auth_service
    locations: classpath:db/migration
    baseline-on-migrate: true
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/clinica_db?currentSchema=auth_service
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET:PrOY3ct0nlyS3cr3tK3yPrOY3ct0nlyS3cr3tK3y}
  expiration: ${JWT_EXPIRATION:86400000}