server:
  port: 8084

spring:
  application:
    name: medical-service
  datasource:
    url: jdbc:postgresql://localhost:5433/clinica_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: doctor_service
    open-in-view: false
  flyway:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

internal:
  gateway:
    secret: ${INTERNAL_GATEWAY_SECRET:5rO2rtldA8350502DreTcvFu9n2s8v7Xo1j6z9w0}

management:
  endpoints:
    web:
      exposure:
        include: health,info
